FROM node as builder

WORKDIR /app

COPY package.json .

ENV REACT_APP_REST=/api

RUN npm install --save --legacy-peer-deps

COPY . .

RUN npm run build

FROM nginx:latest

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /usr/share/nginx/html

